#!/bin/sh
# Write this Mac's primary LAN IPv4 into CollabServerConfig.swift before compile.
# Never fail the Xcode build. Fall back to 192.168.1.159 if detection fails.

FALLBACK_IP="192.168.1.159"

if [ -z "$SRCROOT" ]; then
    SRCROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
fi

OUT="${SRCROOT}/RTABMapApp/Generated/CollabServerConfig.swift"
FALLBACK="${SRCROOT}/RTABMapApp/Generated/CollabServerConfig.fallback.swift"
PLIST="${SRCROOT}/Settings.bundle/Root.plist"

is_ipv4() {
    echo "$1" | grep -Eq '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
}

detect_lan_ip() {
    ip=$(ipconfig getifaddr en0 2>/dev/null || true)
    if is_ipv4 "$ip"; then
        echo "$ip"
        return 0
    fi

    for iface in $(ifconfig -l 2>/dev/null); do
        case "$iface" in
            en*)
                ip=$(ipconfig getifaddr "$iface" 2>/dev/null || true)
                if is_ipv4 "$ip"; then
                    echo "$ip"
                    return 0
                fi
                ;;
        esac
    done

    ifconfig 2>/dev/null | awk '
        /inet / {
            ip = $2
            if (ip != "127.0.0.1" && ip !~ /^169\.254\./) {
                print ip
                exit
            }
        }'
}

IP=$(detect_lan_ip || true)
if ! is_ipv4 "$IP"; then
    IP="$FALLBACK_IP"
fi

URL="http://${IP}:8080"

NEW=$(printf '%s\n' \
    '// Generated by generate_collab_server_config.sh. Do not edit.' \
    'enum CollabServerConfig {' \
    "    static let defaultURL = \"${URL}\"" \
    '}')

if ! mkdir -p "$(dirname "$OUT")" 2>/dev/null; then
    exit 0
fi

if [ ! -f "$OUT" ] || [ "$(cat "$OUT" 2>/dev/null)" != "$NEW" ]; then
    if ! printf '%s\n' "$NEW" > "$OUT"; then
        if [ -f "$FALLBACK" ] && [ ! -f "$OUT" ]; then
            cp "$FALLBACK" "$OUT" 2>/dev/null || true
        fi
    fi
fi

if [ -f "$PLIST" ] && [ -x /usr/libexec/PlistBuddy ]; then
    i=0
    while [ "$i" -le 80 ]; do
        if ! /usr/libexec/PlistBuddy -c "Print :PreferenceSpecifiers:${i}" "$PLIST" >/dev/null 2>&1; then
            break
        fi
        key=$(/usr/libexec/PlistBuddy -c "Print :PreferenceSpecifiers:${i}:Key" "$PLIST" 2>/dev/null || true)
        if [ "$key" = "CollabServerURL" ]; then
            current=$(/usr/libexec/PlistBuddy -c "Print :PreferenceSpecifiers:${i}:DefaultValue" "$PLIST" 2>/dev/null || true)
            if [ "$current" != "$URL" ]; then
                /usr/libexec/PlistBuddy -c "Set :PreferenceSpecifiers:${i}:DefaultValue ${URL}" "$PLIST" >/dev/null 2>&1 || true
            fi
            break
        fi
        i=$((i + 1))
    done
fi

exit 0
